// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: hive.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hive_Ingest_FullMethodName = "/hive.Hive/Ingest"
	Hive_Query_FullMethodName  = "/hive.Hive/Query"
)

// HiveClient is the client API for Hive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Hive service definition
type HiveClient interface {
	// Ingest a document chunk into the Hive
	Ingest(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*Status, error)
	// Query the Hive for relevant documents
	Query(ctx context.Context, in *Search, opts ...grpc.CallOption) (*Result, error)
}

type hiveClient struct {
	cc grpc.ClientConnInterface
}

func NewHiveClient(cc grpc.ClientConnInterface) HiveClient {
	return &hiveClient{cc}
}

func (c *hiveClient) Ingest(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Hive_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hiveClient) Query(ctx context.Context, in *Search, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Hive_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HiveServer is the server API for Hive service.
// All implementations must embed UnimplementedHiveServer
// for forward compatibility.
//
// Hive service definition
type HiveServer interface {
	// Ingest a document chunk into the Hive
	Ingest(context.Context, *Chunk) (*Status, error)
	// Query the Hive for relevant documents
	Query(context.Context, *Search) (*Result, error)
	mustEmbedUnimplementedHiveServer()
}

// UnimplementedHiveServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHiveServer struct{}

func (UnimplementedHiveServer) Ingest(context.Context, *Chunk) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedHiveServer) Query(context.Context, *Search) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedHiveServer) mustEmbedUnimplementedHiveServer() {}
func (UnimplementedHiveServer) testEmbeddedByValue()              {}

// UnsafeHiveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HiveServer will
// result in compilation errors.
type UnsafeHiveServer interface {
	mustEmbedUnimplementedHiveServer()
}

func RegisterHiveServer(s grpc.ServiceRegistrar, srv HiveServer) {
	// If the following call panics, it indicates UnimplementedHiveServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hive_ServiceDesc, srv)
}

func _Hive_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiveServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hive_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiveServer).Ingest(ctx, req.(*Chunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hive_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Search)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiveServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hive_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiveServer).Query(ctx, req.(*Search))
	}
	return interceptor(ctx, in, info, handler)
}

// Hive_ServiceDesc is the grpc.ServiceDesc for Hive service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hive_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hive.Hive",
	HandlerType: (*HiveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _Hive_Ingest_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Hive_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hive.proto",
}
